pipeline {
    agent any

    parameters {
        choice(
            name: 'TEST_ENV',
            choices: ['dev', 'qa'],
            description: 'Select the environment for API tests'
        )
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('API/Playwright-API-Automation') {
                    bat 'npm install'
                }
            }
        }

        stage('Run Playwright Tests') {
            steps {
                dir('API/Playwright-API-Automation') {
                    bat 'set TEST_ENV=%TEST_ENV% && npx playwright test'
                }
            }
        }

        stage('Copy Allure Results') {
            steps {
                dir('API/Playwright-API-Automation') {
                    bat '''
                        xcopy /E /I /Y "allure-results" "%WORKSPACE%\\allure-results"
                    '''
                }
            }
        }
    }

    post {
        always {
            allure([
                results: [[path: 'allure-results']]
            ])
        }
    }
}